name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull debangshu919/reso:latest

      - name: Delete old container
        run: sudo docker rm -f reso-container || true

      - name: Run Docker Container
        run: |
          sudo docker run -d \
            --name reso-container \
            -p 8000:8000 \
            --env-file /home/ubuntu/.env \
            debangshu919/reso:latest
